version: '3.8'

services:
  db:
    container_name: db
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=$DB_PASS
      - POSTGRES_USER=postgres
      - POSTGRES_DB=tk_stats
  php:
    container_name: php
    build:
      context: ./docker/php
    ports:
      - '9000:9000'
    volumes:
      - ./data/php:/var/www/symfony_docker
    depends_on:
      - db
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '$WEB_SERVER_PORT:80'
    volumes:
      - ./data/php:/var/www/symfony_docker
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db
